### ISSUE TITLE
Can you open source this project?

### ISSUE THREAD

**Issue by fsmdeveloper** [Ciarands/vidsrc-keys#7]
First of all, I want to thank you for your awesome project. can you please open-source this project? I want to get the latest vidsrc keys. thank you.

**Comment by Ciarands** [comment]
I intend to open source this in future after I release another project I'm working on, the key extractor will be unusable without me first releasing that project.

**Comment by fsmdeveloper** [comment]
Ok bro! We are waiting for your new project!
