### ISSUE TITLE
Keys no longer updating?

### ISSUE THREAD

**Issue by Inside4ndroid** [Ciarands/vidsrc-keys#8]
the keys seem to have not been update any chance of you checking this?

seems this cause an error on the api :

{"status":404,"return":"Oops reached rate limit of this api"}

Thanks for your awsome work.

**Comment by Gujal00** [comment]
the keys seem to have changed in the last two days
getting
`{"status":200,"result":404}`

@Ciarands can you please check your code as the last time keys were updated was two weeks ago and was working fine till the weekend.

**Comment by Inside4ndroid** [comment]
> the keys seem to have changed in the last two days getting `{"status":200,"result":404}`
> 
> @Ciarands can you please check your code as the last time keys were updated was two weeks ago and was working fine till the weekend.

here is a temp fix with new keys dont know how long they will last though.

https://github.com/Inside4ndroid/vidsrc-keys

**Comment by fsmdeveloper** [comment]
> > the keys seem to have changed in the last two days getting `{"status":200,"result":404}`
> > @Ciarands can you please check your code as the last time keys were updated was two weeks ago and was working fine till the weekend.
> 
> here is a temp fix with new keys dont know how long they will last though.
> 
> https://github.com/Inside4ndroid/vidsrc-keys

Thank you, brother!! How do you get these updated keys? any hint?

**Comment by Inside4ndroid** [comment]
> > > the keys seem to have changed in the last two days getting `{"status":200,"result":404}`
> > > @Ciarands can you please check your code as the last time keys were updated was two weeks ago and was working fine till the weekend.
> > 
> > 
> > here is a temp fix with new keys dont know how long they will last though.
> > https://github.com/Inside4ndroid/vidsrc-keys
> 
> Thank you, brother!! How do you get these updated keys? any hint?

i found these online in a pastebin and they worked lol... i have been trying to de-obfuscate the embed.js from vidplay with no success yet. you could always try goto view-source:https://vidplay.online/e/ and then serch for the embed js open it up and the keys are in there although it need some serious reverse engineering / deobfuscating.

**Comment by Ciarands** [comment]
Sorry about this, I was in Poland for the week with a few friends, im home now, will be able to keep on top of it.

**Comment by Gujal00** [comment]
Dont apologise mate, you have your life and this is just a hobby. Was just alerting you that you may not have noticed. We are thankful for the work you do and not complaining

**Comment by fsmdeveloper** [comment]
> deobfuscating

Thank you, bro. You are such a genius programmer. Please keep the keys updated. My Android app uses your script for fetching HLS URLs for movies and TV series.

**[HDO BOX](https://hdoapp.com)**

**Comment by Inside4ndroid** [comment]
no need to apologise we all have daily life. You do an awesome job. thank you :)

**Comment by fsmdeveloper** [comment]
The current keys are no longer working 😫🥲

**Comment by Inside4ndroid** [comment]
i have updated the keys manually in my repo and created a pull request :)

**Comment by fsmdeveloper** [comment]
> i have updated the keys manually in my repo and created a pull request :)

Thanks, bro! However, I want to know how I can get updated keys. [Ciarands](https://github.com/Ciarands) mentioned that he will open source this project. I'm still waiting for him to take action

**Comment by Inside4ndroid** [comment]
> > i have updated the keys manually in my repo and created a pull request :)
> 
> Thanks, bro! However, I want to know how I can get updated keys. [Ciarands](https://github.com/Ciarands) mentioned that he will open source this project. I'm still waiting for him to take action

I got the keys from a pastebin bro.. I am also waiting for this to be open sourced....
